
SELECT COUNT(*) as SCHEDULE_RECORDS FROM SCHEDULE;
SELECT COUNT(*) as STUDENT_RECORDS FROM STUDENTS;
SELECT COUNT(*) as COURSE_RECORDS FROM COURSES;
SELECT COUNT(*) as INSTRUCTOR_RECORDS FROM INSTRUCTORS;

-- QUERY 1: Find all lessons for a specific course

--   WITHOUT INDEX: Sequential Scan, ~300-500ms, ~500K rows scanned
--   WITH INDEX:    Index Scan, ~2-5ms, ~1K rows scanned

SELECT ID INTO TEMP course_id FROM COURSES LIMIT 1;

EXPLAIN ANALYZE
SELECT 
    c.COURSE_DISPLAY_SHORT_NAME,
    sch.WEEK_DAY,
    ls.START_TIME,
    ls.END_TIME,
    COUNT(*) as LESSON_COUNT
FROM SCHEDULE sch
JOIN COURSES c ON sch.COURSE_ID = c.ID
JOIN LESSONS_SCHEDULE ls ON sch.LESSON_SCHEDULE_ID = ls.ID
WHERE sch.COURSE_ID = (SELECT ID FROM COURSES LIMIT 1)
GROUP BY c.COURSE_DISPLAY_SHORT_NAME, sch.WEEK_DAY, ls.START_TIME, ls.END_TIME;

-- QUERY 2: Find all lessons taught by a specific instructor

--   WITHOUT INDEX: Sequential Scan, ~250-400ms
--   WITH INDEX:    Index Scan, ~1-3ms


EXPLAIN ANALYZE
SELECT 
    i.FIRST_NAME,
    i.LAST_NAME,
    c.COURSE_DISPLAY_SHORT_NAME,
    sch.WEEK_DAY,
    ls.START_TIME,
    r.BUILDING,
    r.DISPLAY_NAME as ROOM_NAME
FROM SCHEDULE sch
JOIN INSTRUCTORS i ON sch.INSTRUCTOR_ID = i.ID
JOIN COURSES c ON sch.COURSE_ID = c.ID
JOIN LESSONS_SCHEDULE ls ON sch.LESSON_SCHEDULE_ID = ls.ID
JOIN ROOMS r ON sch.ROOM_ID = r.ID
WHERE sch.INSTRUCTOR_ID = (SELECT ID FROM INSTRUCTORS LIMIT 1)
ORDER BY sch.WEEK_DAY, ls.START_TIME;


-- QUERY 3: Find all lessons held in a specific room on a specific day

--   WITHOUT INDEX: Sequential Scan, ~280ms, 500K rows scanned
--   WITH INDEX:    Index Scan, ~1-2ms, ~30 rows scanned

EXPLAIN ANALYZE
SELECT 
    c.COURSE_DISPLAY_SHORT_NAME,
    i.FIRST_NAME || ' ' || i.LAST_NAME as INSTRUCTOR_NAME,
    ls.START_TIME,
    ls.END_TIME,
    sch.WEEK_DAY
FROM SCHEDULE sch
JOIN COURSES c ON sch.COURSE_ID = c.ID
JOIN INSTRUCTORS i ON sch.INSTRUCTOR_ID = i.ID
JOIN LESSONS_SCHEDULE ls ON sch.LESSON_SCHEDULE_ID = ls.ID
WHERE sch.ROOM_ID = (SELECT ID FROM ROOMS LIMIT 1)
  AND sch.WEEK_DAY = 'MONDAY'
ORDER BY ls.START_TIME;

-- QUERY 4: Find a student's complete schedule (Complex Join)

-- Expected Results:
--   WITHOUT INDEX: Multiple Sequential Scans, ~150-300ms
--   WITH INDEX:    Multiple Index Scans, ~5-10ms


EXPLAIN ANALYZE
SELECT 
    st.FIRST_NAME || ' ' || st.LAST_NAME as STUDENT_NAME,
    c.COURSE_DISPLAY_SHORT_NAME,
    c.COURSE_DISPLAY_FULL_NAME,
    sch.WEEK_DAY,
    ls.START_TIME,
    ls.END_TIME,
    i.FIRST_NAME || ' ' || i.LAST_NAME as INSTRUCTOR_NAME,
    r.BUILDING,
    r.FLOOR,
    r.NUMBER as ROOM_NUMBER,
    r.DISPLAY_NAME as ROOM_NAME
FROM STUDENTS st
INNER JOIN STUDENTS_COURSE_GROUP_STUDENTS scgs ON st.ID = scgs.STUDENT_ID
INNER JOIN STUDENTS_COURSE_GROUPS scg ON scgs.GROUP_ID = scg.ID
INNER JOIN SCHEDULE sch ON scg.ID = sch.STUDENTS_COURSE_GROUP_ID
INNER JOIN COURSES c ON sch.COURSE_ID = c.ID
INNER JOIN LESSONS_SCHEDULE ls ON sch.LESSON_SCHEDULE_ID = ls.ID
INNER JOIN INSTRUCTORS i ON sch.INSTRUCTOR_ID = i.ID
INNER JOIN ROOMS r ON sch.ROOM_ID = r.ID
WHERE st.ID = (SELECT ID FROM STUDENTS LIMIT 1)
ORDER BY sch.WEEK_DAY, ls.START_TIME;

-- QUERY 5: Composite Index Performance - Schedule queries with multiple filters

--   WITHOUT INDEX: Sequential Scan, ~300ms
--   WITH INDEX:    Index Scan, ~0.5-1ms

EXPLAIN ANALYZE
SELECT 
    COUNT(*) as LESSON_COUNT,
    SUM(CASE WHEN sch.WEEK_DAY IN ('MONDAY', 'WEDNESDAY', 'FRIDAY') THEN 1 ELSE 0 END) as MWF_LESSONS,
    SUM(CASE WHEN sch.WEEK_DAY IN ('TUESDAY', 'THURSDAY') THEN 1 ELSE 0 END) as TTH_LESSONS
FROM SCHEDULE sch
WHERE sch.COURSE_ID = (SELECT ID FROM COURSES LIMIT 1)
  AND sch.WEEK_DAY IN ('MONDAY', 'TUESDAY', 'WEDNESDAY')
  AND sch.LESSON_SCHEDULE_ID IN (1, 2, 3);

-- QUERY 6: Active Students Filter (Index with WHERE clause)

--   WITHOUT INDEX: Sequential Scan, ~20ms, 5K rows scanned
--   WITH INDEX:    Index Scan, ~1ms, ~4.5K rows scanned

EXPLAIN ANALYZE
SELECT 
    COUNT(*) as ACTIVE_STUDENTS,
    AVG(s.COURSE) as AVG_COURSE,
    COUNT(DISTINCT s.EDUCATIONAL_DEGREE) as DEGREE_TYPES
FROM STUDENTS s
WHERE s.ACTIVE = TRUE;

-- QUERY 7: Email Lookup (Unique Index)

--   WITHOUT INDEX: Sequential Scan, ~5ms
--   WITH INDEX:    Index Scan, ~0.1ms (sub-millisecond)

EXPLAIN ANALYZE
SELECT 
    s.ID,
    s.FIRST_NAME,
    s.LAST_NAME,
    s.EMAIL,
    COUNT(DISTINCT scg.ID) as ENROLLED_GROUPS
FROM STUDENTS s
LEFT JOIN STUDENTS_COURSE_GROUP_STUDENTS scgs ON s.ID = scgs.STUDENT_ID
LEFT JOIN STUDENTS_COURSE_GROUPS scg ON scgs.GROUP_ID = scg.ID
WHERE s.EMAIL LIKE '%.edu'
GROUP BY s.ID, s.FIRST_NAME, s.LAST_NAME, s.EMAIL
LIMIT 100;


