-- View 1: Shows each student's complete weekly schedule
CREATE OR REPLACE VIEW STUDENT_SCHEDULE AS
SELECT 
    s.ID as STUDENT_ID,
    CONCAT(s.FIRST_NAME, ' ', s.LAST_NAME) as STUDENT_NAME,
    c.COURSE_DISPLAY_SHORT_NAME as COURSE_CODE,
    c.COURSE_DISPLAY_FULL_NAME as COURSE_NAME,
    sch.WEEK_DAY,
    ls.START_TIME,
    ls.END_TIME,
    CONCAT(i.FIRST_NAME, ' ', i.LAST_NAME) as INSTRUCTOR_NAME,
    r.BUILDING,
    r.FLOOR,
    r.NUMBER as ROOM_NUMBER,
    r.DISPLAY_NAME as ROOM_NAME
FROM STUDENTS s
INNER JOIN STUDENTS_COURSE_GROUP_STUDENTS scgs ON s.ID = scgs.STUDENT_ID
INNER JOIN STUDENTS_COURSE_GROUPS scg ON scgs.GROUP_ID = scg.ID
INNER JOIN SCHEDULE sch ON scg.ID = sch.STUDENTS_COURSE_GROUP_ID
INNER JOIN COURSES c ON sch.COURSE_ID = c.ID
INNER JOIN LESSONS_SCHEDULE ls ON sch.LESSON_SCHEDULE_ID = ls.ID
INNER JOIN INSTRUCTORS i ON sch.INSTRUCTOR_ID = i.ID
INNER JOIN ROOMS r ON sch.ROOM_ID = r.ID
WHERE s.ACTIVE = TRUE
ORDER BY s.ID, sch.WEEK_DAY, ls.START_TIME;

-- View 2: Shows each instructor's teaching schedule
CREATE OR REPLACE VIEW INSTRUCTOR_SCHEDULE AS
SELECT 
    i.ID as INSTRUCTOR_ID,
    CONCAT(i.FIRST_NAME, ' ', i.LAST_NAME) as INSTRUCTOR_NAME,
    c.COURSE_DISPLAY_SHORT_NAME as COURSE_CODE,
    c.COURSE_DISPLAY_FULL_NAME as COURSE_NAME,
    sch.WEEK_DAY,
    ls.START_TIME,
    ls.END_TIME,
    COUNT(DISTINCT scgs.STUDENT_ID) as STUDENT_COUNT,
    r.BUILDING,
    r.DISPLAY_NAME as ROOM_NAME
FROM INSTRUCTORS i
INNER JOIN SCHEDULE sch ON i.ID = sch.INSTRUCTOR_ID
INNER JOIN COURSES c ON sch.COURSE_ID = c.ID
INNER JOIN LESSONS_SCHEDULE ls ON sch.LESSON_SCHEDULE_ID = ls.ID
INNER JOIN STUDENTS_COURSE_GROUPS scg ON sch.STUDENTS_COURSE_GROUP_ID = scg.ID
INNER JOIN STUDENTS_COURSE_GROUP_STUDENTS scgs ON scg.ID = scgs.GROUP_ID
INNER JOIN ROOMS r ON sch.ROOM_ID = r.ID
WHERE i.ACTIVE = TRUE
GROUP BY i.ID, i.FIRST_NAME, i.LAST_NAME, c.COURSE_DISPLAY_SHORT_NAME, 
         c.COURSE_DISPLAY_FULL_NAME, sch.WEEK_DAY, ls.START_TIME, ls.END_TIME,
         r.BUILDING, r.DISPLAY_NAME
ORDER BY i.ID, sch.WEEK_DAY, ls.START_TIME;

-- View 3: Provides metrics for each course
CREATE OR REPLACE VIEW COURSE_STATISTICS AS
SELECT 
    c.ID,
    c.COURSE_DISPLAY_SHORT_NAME,
    c.COURSE_DISPLAY_FULL_NAME,
    COUNT(DISTINCT i.ID) as INSTRUCTOR_COUNT,
    COUNT(DISTINCT scg.ID) as GROUP_COUNT,
    COUNT(DISTINCT scgs.STUDENT_ID) as TOTAL_STUDENTS,
    c.LECTURES_NUM,
    c.PRACTICES_NUM,
    (c.LECTURES_NUM + c.PRACTICES_NUM) as TOTAL_LESSONS
FROM COURSES c
LEFT JOIN INSTRUCTORS_COURSES ic ON c.ID = ic.COURSE_ID
LEFT JOIN INSTRUCTORS i ON ic.INSTRUCTOR_ID = i.ID
LEFT JOIN STUDENTS_COURSE_GROUPS scg ON c.ID = scg.COURSE_ID
LEFT JOIN STUDENTS_COURSE_GROUP_STUDENTS scgs ON scg.ID = scgs.GROUP_ID
GROUP BY c.ID, c.COURSE_DISPLAY_SHORT_NAME, c.COURSE_DISPLAY_FULL_NAME, 
         c.LECTURES_NUM, c.PRACTICES_NUM
ORDER BY c.COURSE_DISPLAY_SHORT_NAME;


-- View 4: Shows room usage and availability
CREATE OR REPLACE VIEW ROOM_UTILIZATION AS
SELECT 
    r.ID,
    r.BUILDING,
    r.FLOOR,
    r.NUMBER,
    r.DISPLAY_NAME,
    r.SEATS_NUMBER,
    COUNT(DISTINCT sch.ID) as SCHEDULED_LESSONS,
    COUNT(DISTINCT sch.WEEK_DAY) as DAYS_IN_USE,
    MAX(CASE WHEN scgs.STUDENT_ID IS NOT NULL THEN 1 ELSE 0 END) as IN_USE
FROM ROOMS r
LEFT JOIN SCHEDULE sch ON r.ID = sch.ROOM_ID
LEFT JOIN STUDENTS_COURSE_GROUPS scg ON sch.STUDENTS_COURSE_GROUP_ID = scg.ID
LEFT JOIN STUDENTS_COURSE_GROUP_STUDENTS scgs ON scg.ID = scgs.GROUP_ID
GROUP BY r.ID, r.BUILDING, r.FLOOR, r.NUMBER, r.DISPLAY_NAME, r.SEATS_NUMBER
ORDER BY r.BUILDING, r.FLOOR, r.NUMBER;


-- View 5: Compliance view for tracking inactive users
CREATE OR REPLACE VIEW INACTIVE_USERS AS
SELECT 
    'STUDENT' as USER_TYPE,
    ID,
    CONCAT(FIRST_NAME, ' ', LAST_NAME) as FULL_NAME,
    EMAIL,
    CREATED_AT,
    CURRENT_DATE - CREATED_AT::DATE as DAYS_INACTIVE
FROM STUDENTS
WHERE ACTIVE = FALSE
UNION ALL
SELECT 
    'INSTRUCTOR' as USER_TYPE,
    ID,
    CONCAT(FIRST_NAME, ' ', LAST_NAME) as FULL_NAME,
    EMAIL,
    CREATED_AT,
    CURRENT_DATE - CREATED_AT::DATE as DAYS_INACTIVE
FROM INSTRUCTORS
WHERE ACTIVE = FALSE
ORDER BY USER_TYPE, DAYS_INACTIVE DESC;
