
DROP TABLE IF EXISTS SCHEDULE CASCADE;
DROP TABLE IF EXISTS STUDENTS_COURSE_GROUP_STUDENTS CASCADE;
DROP TABLE IF EXISTS STUDENTS_COURSE_GROUPS CASCADE;
DROP TABLE IF EXISTS INSTRUCTORS_COURSES CASCADE;
DROP TABLE IF EXISTS LESSONS_SCHEDULE CASCADE;
DROP TABLE IF EXISTS ROOMS CASCADE;
DROP TABLE IF EXISTS COURSES CASCADE;
DROP TABLE IF EXISTS INSTRUCTORS CASCADE;
DROP TABLE IF EXISTS STUDENTS CASCADE;
DROP TABLE IF EXISTS AUDIT_LOG CASCADE;

-- ============================================================================
-- TABLES
-- ============================================================================

CREATE TABLE STUDENTS (
    ID VARCHAR(36) PRIMARY KEY,
    FIRST_NAME VARCHAR(200) NOT NULL,
    LAST_NAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL UNIQUE,
    PHONE VARCHAR(20),
    COURSE INT NOT NULL CHECK (COURSE >= 1 AND COURSE <= 6),
    EDUCATIONAL_DEGREE VARCHAR(20) NOT NULL,
    SPECIALITY VARCHAR(200) NOT NULL,
    ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE INSTRUCTORS (
    ID VARCHAR(36) PRIMARY KEY,
    FIRST_NAME VARCHAR(200) NOT NULL,
    LAST_NAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL UNIQUE,
    PHONE VARCHAR(20),
    ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE COURSES (
    ID VARCHAR(36) PRIMARY KEY,
    COURSE_DISPLAY_SHORT_NAME VARCHAR(36) NOT NULL UNIQUE,
    COURSE_DISPLAY_FULL_NAME VARCHAR(200) NOT NULL,
    COURSE_DESCRIPTION VARCHAR(500),
    LECTURES_NUM INT NOT NULL CHECK (LECTURES_NUM >= 0),
    PRACTICES_NUM INT NOT NULL CHECK (PRACTICES_NUM >= 0),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ROOMS (
    ID VARCHAR(36) PRIMARY KEY,
    BUILDING VARCHAR(200) NOT NULL,
    FLOOR INT NOT NULL CHECK (FLOOR >= 0),
    NUMBER INT NOT NULL,
    DISPLAY_NAME VARCHAR(200),
    SEATS_NUMBER INT NOT NULL CHECK (SEATS_NUMBER > 0),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(BUILDING, FLOOR, NUMBER)
);

CREATE TABLE LESSONS_SCHEDULE (
    ID INT PRIMARY KEY,
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL,
    CHECK (START_TIME < END_TIME)
);

CREATE TABLE INSTRUCTORS_COURSES (
    INSTRUCTOR_ID VARCHAR(36) NOT NULL,
    COURSE_ID VARCHAR(36) NOT NULL,
    PRIMARY KEY (INSTRUCTOR_ID, COURSE_ID),
    FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTORS(ID) ON DELETE CASCADE,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE
);

CREATE TABLE STUDENTS_COURSE_GROUPS (
    ID VARCHAR(36) PRIMARY KEY,
    COURSE_ID VARCHAR(36) NOT NULL,
    GROUP_NUMBER INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    UNIQUE(COURSE_ID, GROUP_NUMBER)
);

CREATE TABLE STUDENTS_COURSE_GROUP_STUDENTS (
    STUDENT_ID VARCHAR(36) NOT NULL,
    GROUP_ID VARCHAR(36) NOT NULL,
    ENROLLED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (STUDENT_ID, GROUP_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(ID) ON DELETE CASCADE,
    FOREIGN KEY (GROUP_ID) REFERENCES STUDENTS_COURSE_GROUPS(ID) ON DELETE CASCADE
);

CREATE TABLE SCHEDULE (
    ID SERIAL PRIMARY KEY,
    COURSE_ID VARCHAR(36) NOT NULL,
    INSTRUCTOR_ID VARCHAR(36) NOT NULL,
    STUDENTS_COURSE_GROUP_ID VARCHAR(36) NOT NULL,
    WEEK_DAY VARCHAR(20) NOT NULL CHECK (WEEK_DAY IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    LESSON_SCHEDULE_ID INT NOT NULL,
    ROOM_ID VARCHAR(36) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTORS(ID) ON DELETE CASCADE,
    FOREIGN KEY (STUDENTS_COURSE_GROUP_ID) REFERENCES STUDENTS_COURSE_GROUPS(ID) ON DELETE CASCADE,
    FOREIGN KEY (LESSON_SCHEDULE_ID) REFERENCES LESSONS_SCHEDULE(ID) ON DELETE CASCADE,
    FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ID) ON DELETE CASCADE
);

CREATE TABLE AUDIT_LOG (
    ID SERIAL PRIMARY KEY,
    TABLE_NAME VARCHAR(50) NOT NULL,
    OPERATION VARCHAR(10) NOT NULL,
    RECORD_ID VARCHAR(36),
    OLD_VALUES JSON,
    NEW_VALUES JSON,
    CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHANGED_BY VARCHAR(100)
);

-- ============================================================================
-- INDEXES 
-- ============================================================================

CREATE INDEX idx_students_email ON STUDENTS(EMAIL);
CREATE INDEX idx_students_course ON STUDENTS(COURSE) WHERE ACTIVE = TRUE;
CREATE INDEX idx_students_active ON STUDENTS(ACTIVE);

CREATE INDEX idx_instructors_email ON INSTRUCTORS(EMAIL);
CREATE INDEX idx_instructors_active ON INSTRUCTORS(ACTIVE);

CREATE INDEX idx_courses_short_name ON COURSES(COURSE_DISPLAY_SHORT_NAME);

CREATE INDEX idx_rooms_building ON ROOMS(BUILDING);
CREATE INDEX idx_rooms_seats ON ROOMS(SEATS_NUMBER);

CREATE INDEX idx_students_course_groups_course ON STUDENTS_COURSE_GROUPS(COURSE_ID);
CREATE INDEX idx_students_group_students_student ON STUDENTS_COURSE_GROUP_STUDENTS(STUDENT_ID);
CREATE INDEX idx_students_group_students_group ON STUDENTS_COURSE_GROUP_STUDENTS(GROUP_ID);

CREATE INDEX idx_instructors_courses_instructor ON INSTRUCTORS_COURSES(INSTRUCTOR_ID);
CREATE INDEX idx_instructors_courses_course ON INSTRUCTORS_COURSES(COURSE_ID);

CREATE INDEX idx_schedule_course ON SCHEDULE(COURSE_ID);
CREATE INDEX idx_schedule_instructor ON SCHEDULE(INSTRUCTOR_ID);
CREATE INDEX idx_schedule_room ON SCHEDULE(ROOM_ID);
CREATE INDEX idx_schedule_week_day ON SCHEDULE(WEEK_DAY);
CREATE INDEX idx_schedule_group ON SCHEDULE(STUDENTS_COURSE_GROUP_ID);

CREATE INDEX idx_schedule_course_day_time ON SCHEDULE(COURSE_ID, WEEK_DAY, LESSON_SCHEDULE_ID);

-- ============================================================================
-- CONSTRAINTS AND TRIGGERS FOR DATA INTEGRITY
-- ============================================================================

CREATE OR REPLACE FUNCTION log_students_changes()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        INSERT INTO AUDIT_LOG (TABLE_NAME, OPERATION, RECORD_ID, OLD_VALUES, CHANGED_BY)
        VALUES ('STUDENTS', TG_OP, OLD.ID, row_to_json(OLD), CURRENT_USER);
        RETURN OLD;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO AUDIT_LOG (TABLE_NAME, OPERATION, RECORD_ID, OLD_VALUES, NEW_VALUES, CHANGED_BY)
        VALUES ('STUDENTS', TG_OP, NEW.ID, row_to_json(OLD), row_to_json(NEW), CURRENT_USER);
        RETURN NEW;
    ELSIF TG_OP = 'INSERT' THEN
        INSERT INTO AUDIT_LOG (TABLE_NAME, OPERATION, RECORD_ID, NEW_VALUES, CHANGED_BY)
        VALUES ('STUDENTS', TG_OP, NEW.ID, row_to_json(NEW), CURRENT_USER);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER students_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON STUDENTS
FOR EACH ROW
EXECUTE FUNCTION log_students_changes();

CREATE OR REPLACE FUNCTION check_room_capacity()
RETURNS TRIGGER AS $$
DECLARE
    room_capacity INT;
    group_size INT;
BEGIN
    SELECT SEATS_NUMBER INTO room_capacity FROM ROOMS WHERE ID = NEW.ROOM_ID;
    
    SELECT COUNT(*) INTO group_size 
    FROM STUDENTS_COURSE_GROUP_STUDENTS 
    WHERE GROUP_ID = NEW.STUDENTS_COURSE_GROUP_ID;
    
    IF group_size > room_capacity THEN
        RAISE EXCEPTION 'Room capacity % is less than group size %', room_capacity, group_size;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER schedule_room_capacity_trigger
BEFORE INSERT OR UPDATE ON SCHEDULE
FOR EACH ROW
EXECUTE FUNCTION check_room_capacity();

CREATE OR REPLACE FUNCTION check_instructor_course()
RETURNS TRIGGER AS $$
DECLARE
    teaches BOOLEAN;
BEGIN
    SELECT EXISTS(
        SELECT 1 FROM INSTRUCTORS_COURSES 
        WHERE INSTRUCTOR_ID = NEW.INSTRUCTOR_ID 
        AND COURSE_ID = NEW.COURSE_ID
    ) INTO teaches;
    
    IF NOT teaches THEN
        RAISE EXCEPTION 'Instructor % does not teach course %', NEW.INSTRUCTOR_ID, NEW.COURSE_ID;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER schedule_instructor_course_trigger
BEFORE INSERT OR UPDATE ON SCHEDULE
FOR EACH ROW
EXECUTE FUNCTION check_instructor_course();
